name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build dev container
        run: ./bin/build-dev-container

      - name: Lint
        run: ./bin/lint

      - name: Test
        run: ./bin/test
