name: publish

on:
  workflow_run:
    workflows:
      - "ci"
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+**
    # types:
    #   - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == "success" }}
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        run: ./bin/publish "$GITHUB_REF_NAME"
